export const MessageTypeEnum = {
  REQUEST_LATEST_BLOCK: "REQUEST_LATEST_BLOCK",
  RECEIVE_LATEST_BLOCK: "RECEIVE_LATEST_BLOCK",
  REQUEST_BLOCKCHAIN: "REQUEST_BLOCKCHAIN",
  RECEIVE_BLOCKCHAIN: "RECEIVE_BLOCKCHAIN",
  REQUEST_TRANSACTIONS: "REQUEST_TRANSACTIONS",
  RECEIVE_LATEST_TRANSACTION: "RECEIVE_LATEST_TRANSACTION",
  RECEIVE_TRANSACTIONS: "RECEIVE_TRANSACTIONS",
  RECEIVE_REMOVE_TRANSACTION: "RECEIVE_REMOVE_TRANSACTION"
};
